apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: markethub-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/websocket-services: "market-stream-service"
spec:
  ingressClassName: nginx
  rules:
  - host: api.markethub.local
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 3001
      - path: /market
        pathType: Prefix
        backend:
          service:
            name: market-stream-service
            port:
              number: 3002
      - path: /booking
        pathType: Prefix
        backend:
          service:
            name: booking-service
            port:
              number: 3003
      - path: /tasks
        pathType: Prefix
        backend:
          service:
            name: task-service
            port:
              number: 3004
  - host: markethub.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
